# docker-compose.yml

services:
  database:
    image: neo4j:5-community
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123